JSQLParser/JSqlParser

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/create/CreateTableTest.java

The parser is crashing if a CREATE TABLE statement contains a inlined foreign key(see testcases).

Fix inline usage of foreign keys in CREATE TABLE statements

---

src/main/java/net/sf/jsqlparser/statement/delete/Delete.java
src/main/java/net/sf/jsqlparser/statement/update/Update.java
src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/LimitDeparser.java
src/main/java/net/sf/jsqlparser/util/deparser/OrderByDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UpdateDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/delete/DeleteTest.java
src/test/java/net/sf/jsqlparser/test/update/UpdateTest.java

Add support for ORDER BY and LIMIT in UPDATE and DELETE statements (as supported by MySQL).
LimitDeparser and OrderByDeParser have been pulled out into separate classes to avoid code duplication from SelectDeParser.

Issue 195: support for ORDER BY and LIMIT, in UPDATE and DELETE statements

---

pom.xml

Added profile to ensure doclint is turned off with Java 8+. Without this, the project won't build on Java 8 (you can run `mvn test` successfully, but not `mvn package`).
The extra maven config allows `mvn package` to work on Java 6/7.

Issue 198: make mvn package work on Java 8+

---

src/main/java/net/sf/jsqlparser/util/AddAliasesVisitor.java
src/main/java/net/sf/jsqlparser/util/SelectUtils.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1192 - String literals should not be duplicated.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1192
George Kankava

squid:S1192 - String literals should not be duplicated

---

src/main/java/net/sf/jsqlparser/expression/OracleHint.java
src/main/java/net/sf/jsqlparser/expression/WithinGroupExpression.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/SupportsOldOracleJoinSyntax.java
src/main/java/net/sf/jsqlparser/parser/CCJSqlParserUtil.java
src/main/java/net/sf/jsqlparser/statement/alter/Alter.java
src/main/java/net/sf/jsqlparser/statement/merge/Merge.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeUpdate.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1213
George Kankava

squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order

---

src/main/java/net/sf/jsqlparser/expression/operators/relational/ExistsExpression.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/InExpression.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/IsNullExpression.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/LikeExpression.java
src/main/java/net/sf/jsqlparser/statement/select/Fetch.java
src/main/java/net/sf/jsqlparser/statement/select/Limit.java

This pull request is focused on resolving occurrences of Sonar rule squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
squid:S2131 - Primitives should not be boxed just for "String" conversion.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AUselessParenthesesCheck
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2131
George Kankava

multiple code improvements 1

---

src/main/java/net/sf/jsqlparser/statement/select/Select.java
src/main/java/net/sf/jsqlparser/statement/select/SubSelect.java
src/main/java/net/sf/jsqlparser/util/deparser/DropDeParser.java

This pull request is focused on resolving occurrences of Sonar rules
squid:S1905 Redundant casts should not be used,
squid:S00122 Statements should be on separate lines,
squid:S1155 Collection.isEmpty() should be used to test for emptiness,
squid:S00105 Tabulation characters should not be used.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1905
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00122
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1155
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS00105
George Kankava

multiple code improvements: squid:S1905, squid:S00122, squid:S1155, squid:S00105

---

src/main/java/net/sf/jsqlparser/expression/operators/relational/ComparisonOperator.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/EqualsTo.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/GreaterThan.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/MinorThan.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/MinorThanEquals.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/NotEqualsTo.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/TestUtils.java
src/test/java/net/sf/jsqlparser/test/select/SpecialOracleTest.java

Added ability to have operators like '>=' or '<=' separated by a space.
This includes:
- Modifying the JJT syntax to support the 'space in the middle' versions of operators (any quantity of whitespace is supported).
- Modifying the various operators to inherit from a new 'ComparisonOperator' class, which handles the (previously NotEqualsTo-only) logic for capturing the form of the operator.
- Giving each of the various operators a constructor that accepts the syntax used.
- Modifying TestUtils to strip comments out before comparing SQL text (necessary because condition07.sql is now passing, and has a comment).
- Updating SpecialOracleTest to indicate 130 tests passing now (condition7.sql now passes).
- Adding a new test specifically for operators into SpecialOracleTest.
NOTE: Because the …

Supporting Oracle operators like '>=' or '<=' with embedded whitespace.

---

src/main/java/net/sf/jsqlparser/statement/select/Join.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/HiveTest.java

HiveQL provides a type of JOIN named LEFT SEMI JOIN as a way to write IN/EXIST clause.
> LEFT SEMI JOIN implements the uncorrelated IN/EXISTS subquery semantics in an efficient way. As of Hive 0.13 the IN/NOT IN/EXISTS/NOT EXISTS operators are supported using subqueries so most of these JOINs don't have to be performed manually anymore. The restrictions of using LEFT SEMI JOIN is that the right-hand-side table should only be referenced in the join condition (ON-clause), but not in WHERE- or SELECT-clauses etc.
More information [here](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Joins)

Add support for Hive's LEFT SEMI JOIN

---

src/main/java/net/sf/jsqlparser/statement/update/Update.java
src/main/java/net/sf/jsqlparser/util/deparser/UpdateDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/update/UpdateTest.java

Implemented:
1. UPDATE .. RETURNING col, col as Alias
2. UPDATE .. RETURNING *
Tested:
3. UPDATE .. ORDER BY .. LIMIT .. RETURNING
4. UPDATE .. RETURNING
Item 4 represents the PostgreSQL UPDATE .. RETURNING Syntax without ORDER BY and LIMIT.
See: https://www.postgresql.org/docs/9.5/static/sql-update.html

Added UPDATE .. RETURNING syntax.

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt

Postgres SQL allow casting to a "double precision" type.  This modification implements this syntax.

Add a double precision cast type

---

src/main/java/net/sf/jsqlparser/expression/LongValue.java

`LongValue.java` calls `java.lang.long.parseLong` without first checking whether the argument parses. This lead to an uncaught `NumberFormatException`: [Oracle Java 7 API specification](http://docs.oracle.com/javase/7/docs/api/java/lang/Long.html#parseLong%28java.lang.String,%20int%29).
This pull request adds a check with a  more helpful exception message and also fix an indentation issue at line no. 38.

LongValue does not catch NumberFormatException

---

src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java
src/test/resources/net/sf/jsqlparser/util/complex-merge-requests.txt

In original code, `TablesNamesFinder` just parse the `selectBody` in a `SubSelect` object. However it would lead to a mistake when a `SubSelect` object has `withItemsList`. This pull request fix it and add the corresponding unit test.
By the way, for the universal of unit test module, this pull request use `Statement` object replacing `Select` object.
Thanks for your reading.

fix bug of TablesNamesFinder when SubSelect has withItemsList

---

src/main/java/net/sf/jsqlparser/statement/alter/Alter.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/alter/AlterTest.java

Hi JsqlParser maintainers!
Postgres currently supports multiple ADD/DROP expressions in a single ALTER statement: https://www.postgresql.org/docs/9.5/static/sql-altertable.html with a syntax like 
```sql
ALTER TABLE mytable ADD COLUMN col1 varchar (255), ADD COLUMN col2 integer;
```
This PR adds support for multiple expressions. The highlights: 
* Most of the logic that previously lived in the `Alter` class now lives in the `AlterExpression` class, and the `Alter` class is more or less a container for multiple `AlterExpression`s. 
* Each `AlterExpression.toString` call will return the entire expression, and the `Alter` class builds the statement by stacking these expression strings. 
* The .jjt file has been updated to move most of the `Alter` logic into `AlterExpression` as well, and now …

Update Alter to support Postgres ADD/DROP expressions

---

src/main/java/net/sf/jsqlparser/statement/delete/Delete.java
src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/TestUtils.java
src/test/java/net/sf/jsqlparser/test/delete/DeleteTest.java

Support for parse delete from table using join to another table like:
DELETE posts
FROM posts
INNER JOIN projects ON projects.project_id = posts.project_id
WHERE projects.client_id = :client_id
This necessitated some changes to the DeleteTest class, specifically:
JSqlParserCC.jjt - changes on grammar of Delete statements.
Delete toString and DeleteDeParser.

Delete from table using join to another table

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/alter/AlterTest.java

Hi again JSqlParser maintainers!
The following types are valid column types for Postgres: 
```
time without time zone
time with time zone
timestamp without time zone
timestamp with time zone
bit varying
xml
interval
```
This PR adds support for those types in `ALTER TABLE` statements, along with tests ensuring that the types can be parsed. I believe that _all_ Postgres types will be supported once this PR is merged.

Support additional Postgres column types for alter table statements

---

src/main/java/net/sf/jsqlparser/statement/create/table/ExcludeConstraint.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/create/CreateTableTest.java

Hi JSqlParser maintainers! 
I needed to be able to support more Postgres Create Table syntax options. Specifically, these cases: 
```
CREATE TABLE foo (col1 integer CHECK (col1 > 100));
CREATE TABLE foo (col1 integer REFERENCES bar.col1);
CREATE TABLE foo (col1 integer CONSTRAINT no_null NOT NULL);
CREATE TABLE foo (col1 integer) WITH (fillfactor=70);
CREATE TABLE foo (col1 integer, EXCLUDE WHERE (col1 > 100));
```
This PR adds support + tests for these cases. 
Thanks again for the great library!

Add support for more Postgres Create Table options

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/JsonExpression.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/JsonOperator.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java

I updated several classes to support PostgreSQL JSON Functions and Operators. Sample queries:
`"SELECT * FROM sales WHERE sale->'items'->>'description' = 'milk';"`
`"SELECT` * FROM sales where sale ->'items' @> '[{\"count\":0}]'"
More info on PostgreSQL operators can be found here:
[https://www.postgresql.org/docs/9.5/static/functions-json.html](https://www.postgresql.org/docs/9.5/static/functions-json.html)

Added support for PostgreSQL JSON Functions and Operators.

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterOperation.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/alter/AlterTest.java

1. optional "COLUMN" keyword in ADD alter operation
2. new alter operation: MODIFY
3. add column specs to alter table column definitions
4. unit tests added to AlterTest.java to cover optional "COLUMN" keyword and MODIFY statements and proper parsing of columnSpecs

Enhance AlterExpression grammar:

---

src/main/java/net/sf/jsqlparser/statement/select/Limit.java
src/main/java/net/sf/jsqlparser/util/deparser/LimitDeparser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java

This is a enhancement fix for bug #288, now **limit** can work with jdbc index parameter and jdbc name parameter. 
I also create some test cases for this.
SELECT * FROM mytable WHERE mytable.col = 9 LIMIT :some_name, 2
SELECT * FROM mytable WHERE mytable.col = 9 LIMIT 1, :some_name
SELECT * FROM mytable WHERE mytable.col = 9 LIMIT :name1, :name2
SELECT * FROM mytable WHERE mytable.col = 9 LIMIT ?1, :name1
SELECT * FROM mytable WHERE mytable.col = 9 LIMIT :name1, ?1
and the same with **Top**
SELECT TOP ?1 * FROM mytable WHERE mytable.col = 9
select top :name1 foo from bar
select top ? foo from bar

support to add jdbc name parameter after LIMIT and TOP keywords

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java

This is a enhancement for LIMIT with ONLY ROW COUNT JDBC parameters.
e.g.
`SELECT * FROM mytable WHERE mytable.col = 9 LIMIT ?1`
OR
`SELECT * FROM mytable WHERE mytable.col = 9 LIMIT :param_name`

add support for LIMIT with only one row count JDBC parameter

---

src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/statement/select/Wait.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java

It looks like there's support for
SELECT FOR UPDATE OF, however, Oracle SQL has a FOR UPDATE (WAIT|NOWAIT) syntax, seen here:
https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_10002.htm#i2126016
I've added support for WAIT (integer).

Support FOR UPDATE WAIT

---

README.md

Adding some clarification under the Building section.

Addressing #427

---

src/main/java/net/sf/jsqlparser/expression/MySQLIndexHint.java
src/main/java/net/sf/jsqlparser/schema/Table.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java

Introduce support for MySQL style index hints (defined in mysql docs [here](https://dev.mysql.com/doc/refman/5.7/en/index-hints.html) ).
Index hints immediately follow the table and optional correlation alias in the target table and join clauses like:
`SELECT t.field FROM table t USE INDEX (index_name) WHERE ...`
...or in joins like:
`SELECT t2.field FROM table t INNER JOIN table_2 t2 IGNORE INDEX (index_name) WHERE ...`
This commit checks for the optionally present index hint as part of the `Table` definition, and I tried to make it as small and minimally invasive as possible.
This fixes issue #374 (which was specifically logged for `FORCE INDEX`) and handles the other flavors of mysql index hinting.
Thanks!

Introduce support for mysql index hints (fixing issue #374)

---

src/main/java/net/sf/jsqlparser/statement/StatementVisitor.java
src/main/java/net/sf/jsqlparser/statement/StatementVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/upsert/Upsert.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UpsertDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/upsert/UpsertTest.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java
src/test/java/net/sf/jsqlparser/util/deparser/StatementDeParserTest.java

Greetings. Right now I am interestead in reading documents related to phoneix SQL so I want to see what I could contribute from it. It seems there is no "upsert" involved in the parser. So I write the
implementation of "Upsert" and several basic test cases.

Add Upsert Grammer

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java

The parser is able to parse expressions such as "a NOT LIKE '%pattern%'", but is not able to parse expressions where the NOT part is before the entire expression.
For example: "NOT a LIKE '%pattern%'.
When parsing the latter, the error is:
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered " "LIKE" "LIKE "" at line 1, column 32.
Was expecting one of: ...
The reason this is important is both because these syntaxes are both valid, and also because the deparser uses the second method.
Therefore, if you parse a query with the first type of expression, then deparse it and parse again, you'll get the same error.

Add support for "NOT LIKE ..." expressions

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java

RLIKE is a synonym of REGEXP, therefore should be treated the same.
https://dev.mysql.com/doc/refman/5.7/en/regexp.html

Added support for RLIKE expressions

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/alter/AlterTest.java

fixes #320

---

src/main/java/net/sf/jsqlparser/expression/AnalyticExpression.java
src/main/java/net/sf/jsqlparser/expression/OrderByClause.java
src/main/java/net/sf/jsqlparser/expression/PartitionByClause.java

Refactor the class `AnalyticExpression`.
Extract the "partition by" and "order by" logics out of `AnalyticExpression` into two new classes, in order to make the code more testable and more readable.

Refactor to make the code more readable and testable

---

src/main/java/net/sf/jsqlparser/statement/truncate/Truncate.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/truncate/TruncateTest.java

- the method for rendering a Truncate command in StatementDeParser.java is empty.  This can cause problems, e.g. I wrote a program to split a file of SQL statements into individual statements and the TRUNCATE commands were missing.  I filled in the module.
- The parser does not accept a CASCADE directive in a TRUNCATE DDL.  I modified the parser to accept CASCADE, added code to Truncate.java to record the CASCADE directive and added code to the toString method to render the CASCADE if present.
example SQL (postgres):
truncate table global_uids CASCADE;
The modified code passes all test

fix parsing and rendering of Truncate

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Teradata SQL allows the user to use "sel" in place of "select".
Example:
sel name, status from accounts
I modified JSqlParserCC.jjt to accept the "sel" keyword as synonymous with Select.
The modified code passes all tests

support teradata shortcut for Select

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

MySQL allows to use the `&&` operator as an alias to the AND operator.
https://dev.mysql.com/doc/refman/8.0/en/logical-operators.html#operator_and
Example:
`SELECT col FROM tbl WHERE tbl.pid = 2 && tbl.status = 1`

add support for && operator

---

src/main/java/net/sf/jsqlparser/statement/StatementVisitor.java
src/main/java/net/sf/jsqlparser/statement/StatementVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/comment/Comment.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/comment/CommentTest.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

Added Oracle COMMENT statement:
```
COMMENT ON TABLE table1 IS 'comment1';
COMMENT ON COLUMN table1.column1 IS 'comment1';
```

Added Oracle COMMENT statement

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/Function.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/ItemsListVisitor.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/ItemsListVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/NamedExpressionList.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/InsertDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/ReplaceDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UpsertDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Some standard SQL functions, especially string functions, use keywords to separate parameters.
I have encountered 
For example,
SELECT 
substring(id, 2, 3),
substring(id from 2 for 3),
substring(id from 2),
trim(BOTH ' ' from 'foo bar '),
trim(LEADING ' ' from 'foo bar '),
trim(TRAILING ' ' from 'foo bar '),
trim(' ' from 'foo bar '),
position('foo' in 'bar'),
overlay('foo' placing 'bar' from 1),
overlay('foo' placing 'bar' from 1 for 2)
FROM mytable
This pull request adds support for these functions.
I have added a test for these named parameters in SelectTest.java
The code passes all tests.

support named parameters

---

src/main/java/net/sf/jsqlparser/statement/create/view/AlterView.java
src/main/java/net/sf/jsqlparser/util/deparser/AlterViewDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/create/AlterViewTest.java

Teradata uses REPLACE VIEW instead of ALTER VIEW

REPLACE VIEW as a synonym to ALTER VIEW

---

src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

Hello @JSQLParser team!
At the very beginning I would like to thank you for supporting this awesome framework! I spent hours to compile ANTLR grammars for MySQL to finally drop it because it was unable to do what I needed. The JSqlParser, from the other hand, did a job marvellously!
This pull request is to fix small problem I found when working with `TablesNamesFinder`.

Add support for truncate table

---

src/main/java/net/sf/jsqlparser/statement/select/Join.java
src/main/java/net/sf/jsqlparser/statement/select/KSQLJoinWindow.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/KSQLTest.java
src/test/java/net/sf/jsqlparser/test/TestUtils.java

[KSQL](https://github.com/confluentinc/ksql) supports the 'WITHIN' keyword for stream-stream joins. The syntax is as follows:
```
WITHIN [(before TIMEUNIT, after TIMEUNIT) | N TIMEUNIT]
```
See the [syntax reference](https://docs.confluent.io/current/ksql/docs/developer-guide/syntax-reference.html#create-stream-as-select)
This PR adds support for the WITHIN statement inside a join.

Support KSQL's WITHIN

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

Support parsing `ALTER TABLE Persons DROP CONSTRAINT IF EXISTS UC_Person` as allowed by PostgreSQL

Support Alter Table Drop Constraint If Exists

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

Support parsing `ALTER TABLE Persons ADD UNIQUE (ID)` as described at https://www.w3schools.com/sql/sql_unique.asp and also allowed by PostgreSQL

Support Alter Table Add Unique Constraint

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Example:
SELECT CAST(contact_id AS SIGNED INTEGER) FROM contact WHERE contact_id = 20;
Casting to a SIGNED INTEGER isn't supported while casting to other types like UNSIGNED INTEGER is supported. Now allowing SIGNED INTEGER in a CAST operation as well.

Add support for casting to signed integer

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

Added support for 'ALTER TABLE CHANGE COLUMN oldName newName columnDefinition'. 
Please see https://dev.mysql.com/doc/refman/8.0/en/alter-table.html for reference.
I was not really sure how to modify the AlterStatement class. I found introducing these two new fields was the easiest solution, but I am open to suggestions should there be a better way of doing it.
Also, this is my first time writing anything in JavaCC, so if I've made some obvious mistakes or bad practises, I would gladly take feedback. 
This should fix #380 and parts of #571

Added support for 'ALTER TABLE CHANGE COLUMN'

---

src/main/java/net/sf/jsqlparser/statement/select/Join.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/parser/CCJSqlParserUtilTest.java
src/test/java/net/sf/jsqlparser/parser/JSQLParserExceptionTest.java
src/test/java/net/sf/jsqlparser/schema/DatabaseTest.java
src/test/java/net/sf/jsqlparser/schema/ServerTest.java
src/test/java/net/sf/jsqlparser/statement/BlockTest.java
src/test/java/net/sf/jsqlparser/statement/create/CreateTableTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

Support for simple outer joins.
See https://www.ibm.com/support/knowledgecenter/en/SSGU8G_12.1.0/com.ibm.sqlt.doc/ids_sqt_163.htm
This fixes partially #364
e.g. SELECT DISTINCT t1.f1, t2.f2 FROM t1, OUTER t2 WHERE t1.f3=1 AND t1.f4=t2.f4
Hopefully the code coverage is now improved.

Support for simple informix outer joins.

---

src/main/java/net/sf/jsqlparser/statement/create/index/CreateIndex.java
src/main/java/net/sf/jsqlparser/statement/create/table/Index.java
src/main/java/net/sf/jsqlparser/util/deparser/CreateIndexDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/create/CreateIndexTest.java

The postgresql CREATE INDEX statement uses the USING clause to indicate the indexing method, e.g.
CREATE INDEX myindex1 ON mytab USING GIST (mycol)
This PR adds support for this syntax.
The PR passes all tests, and a test has been added for the USING syntax.
testCreateIndexIssue633 in CreateIndexTest.java will likely now pass.
Most other SQL dialects indicate the indexing method in the parameters between CREATE and INDEX
CREATE (parameter)* INDEX
and in some cases, there can be two parameters, e.g. in TransactSQL one can say
CREATE Unique Clustered INDEX
The current code will only pick up "Unique" for Index.type and will drop "Clustered".
In general, Index.type should be List

support postgresql create index syntax

---

src/main/java/net/sf/jsqlparser/statement/select/KSQLWindow.java
src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/KSQLTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

[KSQL](https://github.com/confluentinc/ksql) supports `WINDOW` keyword for windowed queries in aggregation. The syntax is as follows for different queries:
* Hopping window:
```
WINDOW HOPPING (SIZE 30 SECONDS, ADVANCE BY 10 SECONDS)
```
* Session window:
```
WINDOW SESSION (60 SECONDS)
```
* Tumbling window:
```
WINDOW TUMBLING (SIZE 5 MINUTES)
```
See the syntax reference [here](https://docs.confluent.io/current/ksql/docs/developer-guide/syntax-reference.html#create-stream-as-select).
This PR adds support for KSQL `WINDOW`.

Support KSQL's WINDOW

---

src/main/java/net/sf/jsqlparser/expression/operators/relational/FullTextSearch.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Adding support for the default mode for full text search (without explicitly choosing the mode in the AGAINST clause).
Explicit mode example:
`SELECT col FROM tbl WHERE MATCH (col1,col2,col3) AGAINST ('test' IN NATURAL LANGUAGE MODE)`
Default mode usage example:
`SELECT col FROM tbl WHERE MATCH (col1,col2,col3) AGAINST ('test')`

Support default mode in full text search

---

src/main/java/net/sf/jsqlparser/statement/select/Join.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Added support for the STRAIGHT_JOIN join type.
Parsing failed this far for queries like the following:
SELECT col FROM tbl STRAIGHT_JOIN tbl2 ON tbl.id = tbl2.id

Add support for STRAIGHT_JOIN

---

src/main/java/net/sf/jsqlparser/statement/select/Join.java
src/main/java/net/sf/jsqlparser/statement/select/SubJoin.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

For this query:
`SELECT COUNT(DISTINCT `tbl1`.`id`) FROM (`tbl1`, `tbl2`, `tbl3`)`
When parsing and deparsing, the output is:
`SELECT COUNT(DISTINCT `tbl1`.`id`) FROM (`tbl1` `tbl2` `tbl3`)`
Note the missing commas between the table names in the FROM clause.
This pull request fixes that issue.

When calling toString on subjoin with joins, the result is not as expected

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Expressions such as `INTERVAL <column> DAY` weren't supported this far, because of the `<column>` part. This pull request adds support for such expressions.
Query sample:
`SELECT DATE_ADD(start_date, INTERVAL duration MINUTE) AS end_datetime FROM appointment`

Add support for columns in INTERVAL expressions

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Some databases, such as MySQL, allow complex expressions in the ORDER BY clause. This far, such expressions (equality expressions, LIKE expression, etc.), weren't supported in the ORDER BY clause. This PR enhances the OrderByElement to support such expressions.
Sample query:
`SELECT col FROM tbl tbl_alias ORDER BY tbl_alias.id = 1 DESC`

Adding support for complex expressions in the ORDER BY clause

---

src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

In MySQL, the STRAIGHT_JOIN flag can be used in both the FROM clause and the SELECT clause.
This pull request adds support for this flag in the SELECT clause.
A sample of a valid query:
`SELECT STRAIGHT_JOIN col, col2 FROM tbl INNER JOIN tbl2 ON tbl.id = tbl2.id`

Adding support for STRAIGHT_JOIN in the select clause

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

The following wasn't supported by the parser this far, because of the "AS SIGNED" expression:
`SELECT CAST(contact_id AS SIGNED) FROM contact WHERE contact_id = 20;`
Similar expressions like `AS SIGNED INTEGER` are supported, but the parser expects a data type after the `SIGNED` keyword, which isn't mandatory according to the docs.
More examples can be seen in the documentation (search for "as SIGNED"):
https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html

Adding support for casting to SIGNED

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

This far, only columns or constants were supported in an INTERVAL expression.
Now adding support for simple expressions, such as function calls and addition/subtraction expressions.
Parsing this query failed before this fix:
`SELECT DATE_SUB(mydate, INTERVAL DAY(anotherdate) - 1 DAY) FROM tbl`

Adding support for simple expressions in INTERVAL expressions

---

src/main/java/net/sf/jsqlparser/statement/StatementVisitor.java
src/main/java/net/sf/jsqlparser/statement/StatementVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/alter/sequence/AlterSequence.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/AbstractDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/AlterSequenceDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/CreateSequenceDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterSequenceTest.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

Part of #112 
Did a little refactoring mostly around the deparser (sharing a common class) and made a common production for SequenceProperties (both alter/create can use it).
Once this is merged, I'll follow up with a DROP SEQUENCE pr, and that should complete the sequences feature (at least for oracle syntax)

Support ALTER SEQUENCE 

---

src/main/java/net/sf/jsqlparser/statement/CreateFunctionalStatement.java
src/main/java/net/sf/jsqlparser/statement/StatementVisitor.java
src/main/java/net/sf/jsqlparser/statement/StatementVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/create/function/CreateFunction.java
src/main/java/net/sf/jsqlparser/statement/create/procedure/CreateProcedure.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/create/CreateFunctionalStatementTest.java

Fixes #251 
Fixes #111
Provides very minimal support for function/procedure parsing, returning everything after `FUNCTION` and `PROCEDURE` as a String (or List<Strings> if desired for other formatting)

Minimal function/procedure support

---

src/main/java/net/sf/jsqlparser/statement/comment/Comment.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/comment/CommentTest.java

* implement COMMENT ON VIEW
* testcase "testCommentOnView"
https://github.com/JSQLParser/JSqlParser/issues/1023

COMMENT ON VIEW

---

pom.xml

When importing the Maven project into Eclipse, the sources generated are not automatically included. This commit aims to do that.

Add generated sources to classpath.

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/resources/RUBiS-create-requests.txt

As it is in the issues above, sqls below won't parse.
```sql
SELECT column IS NOT NULL FROM table;
SELECT 0 IS NULL;
```
Then I figured out that in function `SelectExpressionItem()` -> `SimpleExpression()` should be replaced by `Condition()` since null expression, bool expression and SimpleExpression itself are handled in `Condition()`.
Because function `PivotSingleInItems()` also use `SelectExpressionItem()`, I copyed the original `SelectExpressionItem()` so that the "pivot" test doesn't break.
All tests passed, but "SELECT 1 < 2 AS a, (0 IS NULL) AS b" won't work because something is wrong with aliasing an  expression with parentheses. 
"SELECT (1 < 2) AND (3 < 4)" won't work too, I belive this can be fixed somehow in function `Condition()`.

bugfix #720 #991: supporting SELECT "conditions"

---

src/main/java/net/sf/jsqlparser/statement/select/OrderByElement.java
src/test/java/net/sf/jsqlparser/util/RandomUtils.java

see https://github.com/JSQLParser/JSqlParser/pull/1014

Addons/fixes for Fluent API 

---

src/main/java/net/sf/jsqlparser/expression/TimestampValue.java
src/test/java/net/sf/jsqlparser/expression/TimestampValueTest.java

Currently we only keep a reference to a parsed java.sql.Timestamp, but java.sql.Timestamp.valueOf uses local machine Timezone to parse the timestamp value, this is not good for statement rewriting if jSQLParser is running on a separate machine (like a server) with different JVM configuration

Retain original value in TimestampValue

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

This change will allow parsing queries such as:
`SELECT * FROM Case`

Added support for the Case keyword in table names

---

src/main/java/net/sf/jsqlparser/statement/create/table/CreateTable.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/create/CreateTableTest.java

Support `CREATE TABLE` parameters without columns definition, parameter values any names
```
CREATE TEMPORARY TABLE t1 
WITH (APPENDONLY=true,ORIENTATION=column,COMPRESSTYPE=zlib,OIDS=FALSE) ON COMMIT DROP
AS SELECT column FROM t2
```
https://www.postgresql.org/docs/current/sql-createtable.html
Example based on greenplum query
https://gpdb.docs.pivotal.io/6-13/ref_guide/sql_commands/CREATE_TABLE.html

Support CREATE TABLE parameters without columns definition, parameter values any names

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Partial support construct tuple as simple expression
`SELECT hyperloglog_distinct((f1, f2)) FROM t`
https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ROW-CONSTRUCTORS
> The key word ROW is optional when there is more than one expression in the list.

Partial support construct tuple as simple expression

---

src/main/java/net/sf/jsqlparser/expression/ArrayConstructor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/create/CreateTableTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Array constructor support
array[[1, 2], [id1, id2]]
https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ARRAY-CONSTRUCTORS

Array contructor support

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/KSQLTest.java

The new release of JSQLParser breaks in case of singular Time units usage. For example usage of `MINUTE` was failing but `MINUTES` was fine. This bug fix would allow us to use both singular and plural time units.

KSql 'Within' Clause  Time Unit Bug Fix

---

src/main/java/net/sf/jsqlparser/expression/ArrayExpression.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

subArray support arr[1:3]
https://www.postgresql.org/docs/current/arrays.html
We can also access arbitrary rectangular slices of an array, or subarrays. An array slice is denoted by writing lower-bound:upper-bound

subArray support arr[1:3]

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Added support for functions in an interval expression. This far, only columns and JDBC parameters were supported.
A sample query that is now supported:
`SELECT DATE_ADD(start_date, INTERVAL COALESCE(duration, 21) MINUTE) AS end_datetime FROM appointment`

Add support for functions in an interval expression

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

The parser misplaces the LIMIT clause when parsing a UNION query that doesn't include brackets.
The original query:
`select col from tbl union distinct select col2 from tbl order by test limit 100;`
The query after parsing (before the fix):
`SELECT tbl.col FROM tbl UNION DISTINCT SELECT tbl.col2 FROM tbl LIMIT 100 ORDER BY test`
Note that the LIMIT clause shows up before the ORDER BY clause, which is invalid.
After the fix, the query parses as the same as the original query.
Fixes #1018
Fixes #1116

Add support for union without brackets and with limit

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

When parsing the following statement, the ORDER BY clause of the last part of the union was wrongfully considered as if it was the global ORDER BY clause of the union.
Original query:
`(SELECT a FROM tbl ORDER BY a) UNION DISTINCT (SELECT a FROM tbl ORDER BY a)`
Before fixing the issue, the query was parsed to:
`(SELECT a FROM tbl ORDER BY a) UNION DISTINCT (SELECT a FROM tbl) ORDER BY a`
Now after this fix, it will be parsed to the same as the original query.
Fixes #1130

Add support for UNION with brackets and ORDER BY

---

nb-configuration.xml
src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/java/net/sf/jsqlparser/statement/delete/Delete.java
src/main/java/net/sf/jsqlparser/statement/insert/Insert.java
src/main/java/net/sf/jsqlparser/statement/merge/Merge.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeInsert.java
src/main/java/net/sf/jsqlparser/statement/update/Update.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java
src/test/java/net/sf/jsqlparser/statement/create/CreateIndexTest.java
src/test/java/net/sf/jsqlparser/statement/delete/DeleteTest.java
src/test/java/net/sf/jsqlparser/statement/insert/InsertTest.java
src/test/java/net/sf/jsqlparser/statement/merge/MergeTest.java
src/test/java/net/sf/jsqlparser/statement/update/UpdateTest.java
src/test/java/net/sf/jsqlparser/test/TestUtils.java

Implement Oracle Hints for INSERT, UPDATE, MERGE, DELETE

Assorted fixes to the Java CC Parser definition

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/Function.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

function order by support
PostgreSQL ordered aggregates
`SELECT array_agg(s ORDER BY b) FROM t`
https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES

function order by support

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/JsonExpression.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Adding support for column type casts in JSON expressions. For example:
`SELECT id FROM tbl WHERE p.company::json->'info'->>'country' = 'test'`
These casts are supported in PostgreSQL.

Add support for casts in json expressions

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/conditional/XorExpression.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapterTest.java
src/test/java/net/sf/jsqlparser/statement/builder/JSQLParserFluentModelTests.java
src/test/java/net/sf/jsqlparser/statement/builder/ReflectionModelTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java
src/test/java/net/sf/jsqlparser/util/validation/ValidationTest.java

The boolean operator `XOR` (exclusive or) is not part of the SQL standard, but many databases have support for them (ex. mySQL).
However, with the current parser these expressions cannot be parsed as the keyword and the expression for it is not part of the grammar.
This pull request adds support for the XOR Expression, that is treated as a Binary Conditional Operator.
The expression behaves the same as the usual `AND` or `OR` expressions, but its precedence is the lowest: `AND` > `OR` > `XOR`.

Add support for boolean 'XOR' operator

---

README.md
nb-configuration.xml
src/main/java/net/sf/jsqlparser/statement/select/WithItem.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/SelectValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/java/net/sf/jsqlparser/util/deparser/StatementDeParserTest.java

Nested with items

---

src/main/java/net/sf/jsqlparser/statement/delete/Delete.java
src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/delete/DeleteTest.java

Hello,
It is currently possible to analyze this query:
delete a where z=1
However, it fails if the schema is determined:
delete a.b where z=1

Delete queries without from, with a schema identifier fails

---

src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Do not use Brackets for Parameter Lists unless requested explicitly.
Synchronize Function/Expression List Deparser with toString() methods.
Fixes issue #1239

Fixes Function Parameter List Brackets issue #1239

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Fixes issue #1249
(Although there are more Special Registers which are not supported yet.)

Implement DB2 Special Register Date Time CURRENT DATE and CURRENT TIME

---

pom.xml

This will generate the BNF documentation on the Maven Site:
I still will need to create a sensible Stylesheet for it and maybe write a Sanitizer for the HTML page and add Railway diagrams.

Active JJDoc and let it create the Grammar BNF documentation

---

src/main/java/net/sf/jsqlparser/statement/StatementVisitor.java
src/main/java/net/sf/jsqlparser/statement/StatementVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/alter/RenameTableStatement.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/StatementValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/RenameTableStatementTest.java

Implements Oracle RENAME oldTable TO newTable Statement

---

src/main/java/net/sf/jsqlparser/expression/Function.java
src/main/java/net/sf/jsqlparser/parser/CCJSqlParserUtil.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Separate MySQL Special String Functions accepting Named Argument Separation as this could collide with ComplexExpressionList when InExpression is involved
```SQL
-- this is a ComplexExpressionList which must NOT be parsed as NamedParameterList
SELECT test('foo' in ('bar') and 1=1); 
-- this is a NamedParameterList but only for a few Special String Functions
SELECT substring('foo' in 'bar'); 
```
Fixes #1284

Separate MySQL Special String Functions colliding with InExpression

---

src/main/java/net/sf/jsqlparser/expression/CastExpression.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/RowConstructor.java
src/main/java/net/sf/jsqlparser/statement/create/table/ColumnDefinition.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/CastExpressionTest.java
src/test/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapterTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/java/net/sf/jsqlparser/util/validation/ValidationTest.java

Fixes #1267 Cast into RowConstructor
```sql
SELECT CAST(ROW(dataid, value, calcMark) AS ROW(datapointid CHAR, value CHAR, calcMark CHAR))
```

Fixes #1267 Cast into RowConstructor

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/OracleNamedFunctionParameter.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/OracleNamedFunctionParameterTest.java

Fixes #1270
```sql
exec dbms_stats.gather_schema_stats(
ownname          => 'COMMON', 
estimate_percent => dbms_stats.auto_sample_size, 
method_opt       => 'for all columns size auto', 
degree           => DBMS_STATS.DEFAULT_DEGREE,
cascade          => DBMS_STATS.AUTO_CASCADE,
options          => 'GATHER AUTO'
);
```

Implement Oracle Named Function Parameters Func( param1 => arg1, ...)

---

src/main/java/net/sf/jsqlparser/statement/StatementVisitor.java
src/main/java/net/sf/jsqlparser/statement/StatementVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterSystemOperation.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterSystemStatement.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/StatementValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterSystemTest.java

Extremely dull stuff, but the statements:
`ALTER SYSTEM KILL SESSION ...`
`ALTER SYSTEM DISCONNECT SESSION ...`
`ALTER SYSTEM SET ...`
can be quite useful and are used in SQL scripts.

Implement Oracle's Alter System

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterOperation.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

in order to allow:
```sql
ALTER TABLE ... MOVE TABLESPACE ...
ALTER TABLE ... COMPRESS NOLOGGING
ALTER TABLE ... ROWFORMAT=DYNAMIC
```
(and similar syntax. We do not parse the details but only forward the provided tokens.)
Fixes #1033

Add some flexibility to the Alter Statement

---

build.gradle
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Nested Cases with Complex Expressions
Fixes #1306
`GROUP BY` uses Complex Expressions List
Fixes #1308

Fixes #1306

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Removes redundant production Identifier() and uses RelObjectnameWithoutValue() instead for MS SQL Server Hints
Fixes #1325

Fixes #1325

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/create/CreateTableTest.java

This test query is failing so far:
CREATE TABLE temp.abc AS (SELECT c FROM t1) UNION (SELECT c FROM t2)

CREATE TABLE AS (...) UNION (...) fails

---

build.gradle
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/InExpression.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapterTest.java
src/test/java/net/sf/jsqlparser/statement/builder/JSQLParserFluentModelTests.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/condition12.sql

Allows `IN()` to uses Complex Expression Lists including multiple `SubSelects`
Simplifies the `IN()` Statement by removing the Multi Expression List property
Fixes #905

IN() with complex expressions

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Allow Complex Expressions as SelectItem
Fixes #1381
```sql
SELECT ( 1 = 1 ) AND ( 1 = 2 )
```
Fixes #602

Fixes #1381

---

src/main/java/net/sf/jsqlparser/statement/delete/Delete.java
src/main/java/net/sf/jsqlparser/statement/delete/DeleteModifierPriority.java
src/main/java/net/sf/jsqlparser/statement/update/Update.java
src/main/java/net/sf/jsqlparser/statement/update/UpdateModifierPriority.java
src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UpdateDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/delete/DeleteTest.java
src/test/java/net/sf/jsqlparser/statement/update/UpdateTest.java

- Fixes https://github.com/JSQLParser/JSqlParser/issues/1254
- Add IGNORE parser/deparse for DELETE and UPDATE.
- I find also two modifiers not available for MySQL so I also add LOW_PRIORITY modifier for DELETE and UPDATE, and QUICK modifier for DELETE.
- Documentation : https://dev.mysql.com/doc/refman/8.0/en/update.html https://dev.mysql.com/doc/refman/8.0/en/delete.html
- Example queries:
```sql
UPDATE IGNORE table1 A SET A.columna = 'XXX'
DELETE IGNORE FROM tablename
UPDATE LOW_PRIORITY table1 A SET A.columna = 'XXX'
DELETE LOW_PRIORITY FROM tablename
DELETE QUICK FROM tablename
```

Add Delete / Update modifiers for MySQL #1254

---

pom.xml

#1401 add junit-jupiter-api

---

src/main/java/net/sf/jsqlparser/statement/UseStatement.java
src/main/java/net/sf/jsqlparser/statement/create/table/CreateTable.java
src/main/java/net/sf/jsqlparser/util/deparser/CreateTableDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UseStatementDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/LimitExpressionTest.java
src/test/java/net/sf/jsqlparser/statement/UseStatementTest.java
src/test/java/net/sf/jsqlparser/statement/create/CreateTableTest.java

To parse out Snowflake DDL that we use I needed to extend the allowed syntax for USE SCHEMA <schema> and CREATE OR REPLACE <table>

added USE SCHEMA <schema> and CREATE OR REPLACE <table> support

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

PostgreSQL allows double quoting type names in "::" casting operations.
Note how "enum_test" is double quoted in this sample query, and it's valid to do it with built in types like "text" as well:
`SELECT col FROM test WHERE status = CASE WHEN anothercol = 5 THEN 'pending'::"enum_test" END`
Adding support for double quotes around the cast type.

Add support for quoted cast expressions

---

src/main/java/net/sf/jsqlparser/expression/TimezoneExpression.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

This far only 'strings' were supported as part of an AT TIME ZONE expression.
Now supporting columns and more complex expressions, in case one wants to use them as a timezone name.
For example:
`SELECT 1 FROM tbl WHERE col AT TIME ZONE timezone_col < '2021-11-05 00:00:35'::date + INTERVAL '1 day' * 0`

Add support for expressions (such as columns) in AT TIME ZONE expressions

---

pom.xml
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/TryCastExpression.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

MR request for issue #1390 Unable to parse snowflake's TRY_CAST() function

Fix issue in parsing TRY_CAST() function

---

src/main/java/net/sf/jsqlparser/schema/Sequence.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterSequenceTest.java

- Since PostgreSQL 8.4, RESTART in ALTER SEQUENCE can be set without value (https://stackoverflow.com/a/13820203/1535159)
- Add a case for #1405

Support RESTART without value

---

build.gradle
gradle.properties
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/java/net/sf/jsqlparser/statement/select/SpeedTest.java

After JUnit 5 migration, tests were not found when building with Gradle. This PR fixes the issue and adds smaller Gradle goodies. 
Clean Gradle build takes on 4 seconds (when cached).
Clean Maven PACKAGE takes 50 seconds.
Parallel Test execution
Gradle Caching
Explicitly request for latest JavaCC 7.0.10
Fixes #1398

Adjust Gradle to JUnit 5

---

src/main/java/net/sf/jsqlparser/statement/select/SetOperationList.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Fixes #1455 
The `fetch` and `with ur` present in the end of a UNION query should be associated with the UNION query as a whole.

fix fetch present in the end of union query

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/IsDistinctExpression.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

PostgreSQL supports IS DISTINCT FROM clauses as part of conditions.
https://wiki.postgresql.org/wiki/Is_distinct_from
Adding a new type of expression to hold these expressions.
Example:
`SELECT name FROM tbl WHERE name IS DISTINCT FROM foo`

Add support for IS DISTINCT FROM clause

---

src/main/java/net/sf/jsqlparser/statement/select/Top.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

- Add the support of WITH TIES option in SELECT TOP statement.
- Closes #1435

Support WITH TIES option in TOP #1435

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/GeometryDistance.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Adding support for PostGIS geometry distance operators:
* https://postgis.net/docs/geometry_distance_knn.html
* https://postgis.net/docs/geometry_distance_box.html

Add geometry distance operator

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java
src/test/java/net/sf/jsqlparser/statement/select/SpeedTest.java

`RENAME ... TO ...` without `COLUMN` keyword, e. g.
``` sql
ALTER TABLE tableName RENAME col1 TO col2;
```
Fixes #1516

#1516 rename without column keyword

---

README.md
src/main/java/net/sf/jsqlparser/statement/insert/Insert.java
src/main/java/net/sf/jsqlparser/statement/select/Select.java
src/main/java/net/sf/jsqlparser/util/deparser/InsertDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/feature/H2Version.java
src/main/java/net/sf/jsqlparser/util/validation/feature/MariaDbVersion.java
src/main/java/net/sf/jsqlparser/util/validation/feature/MySqlVersion.java
src/main/java/net/sf/jsqlparser/util/validation/feature/OracleVersion.java
src/main/java/net/sf/jsqlparser/util/validation/feature/PostgresqlVersion.java
src/main/java/net/sf/jsqlparser/util/validation/feature/SQLVersion.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/insert/InsertTest.java
src/test/java/net/sf/jsqlparser/util/validation/validator/InsertValidatorTest.java

Simplify the INSERT production
Use SetOperations for Select and Values
Better Bracket handling for WITH ... SELECT ...
Fixes #1491
Following statements will work now:
```sql
(
with a as (select * from dual) 
select * from a
);
insert into table1 (tf1,tf2,tf2) (   
(select sf1,sf2,sf3 from s1)
union (select rf1,rf2,rf2 from r1)
);
```

INSERT with SetOperations

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

This allows to parse statements such as:
`SELECT col FROM tbl cs`

Allow isolation keywords as column name and aliases

---

src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/compound_statements01.sql
src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/compound_statements02.sql
src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/compound_statements03.sql

Hey!
I didn't see any tests for anonymous statement blocks so figured I'd add them!
So I added three new tests for compound statements / anonymous blocks
- https://docs.oracle.com/cd/E17952_01/mysql-5.7-en/begin-end.html
- https://blogs.oracle.com/connect/post/building-with-blocks
Note in the SQL files it says that the tests failed...but `mvn test` doesn't seem to show that at all? Not sure what I'm doing wrong, but wanted to make a PR anyway to see if the failures are legit?

compound statement tests

---

README.md
src/main/java/net/sf/jsqlparser/statement/select/Join.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/join21.sql

Fixes #1559
Make NATURAL an optional Join Keyword, which can be combined with LEFT, RIGHT, INNER
Add tests

Postgres NATURAL LEFT/RIGHT joins

---

src/main/java/net/sf/jsqlparser/statement/select/GroupByElement.java
src/main/java/net/sf/jsqlparser/util/deparser/GroupByDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/HiveTest.java

[Hive dialect](https://cwiki.apache.org/confluence/display/Hive/Enhanced+Aggregation%2C+Cube%2C+Grouping+and+Rollup#EnhancedAggregation,Cube,GroupingandRollup-GROUPINGSETSclause) requires all columns appear in GROUPING SETS clause to be in GROUP BY clause.
```
SELECT a, b, SUM( c ) FROM tab1 GROUP BY a, b GROUPING SETS ( (a, b), a, b, ( ) )
```

Add support for Hive dialect GROUPING SETS.

---

src/test/java/net/sf/jsqlparser/expression/operators/relational/LikeExpressionTest.java

Hey 😊
I want to contribute a test.
Curious to hear what you think!
(I wrote this test as part of a research study at TU Delft. [Find out more](https://github.com/lacinoire/lacinoire/blob/main/README.md))

Add test for LikeExpression.setEscape and LikeExpression.getStringExpression

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/parser/CCJSqlParserUtilTest.java
src/test/java/net/sf/jsqlparser/statement/create/CreateTableTest.java

Support table option character set and index options

---

src/main/java/net/sf/jsqlparser/statement/truncate/Truncate.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/truncate/TruncateTest.java

Implemented Postgresql optional TABLE in TRUNCATE.
Closes #1583

Closes #1583:: Implement Postgresql optional TABLE in TRUNCATE

---

README.md
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/PostgresTest.java

Extended support Postgres' `Extract( field FROM source)` where `field` is a String instead of a Keyword
Fixes #1582
Amend the ExtractExpression
Add Test case for issue #1582
Amend the README

Extended support Postgres' Extract( field FROM source)

---

README.md
src/main/java/net/sf/jsqlparser/parser/AbstractJSqlParser.java
src/main/java/net/sf/jsqlparser/parser/CCJSqlParserUtil.java
src/main/java/net/sf/jsqlparser/parser/feature/Feature.java
src/main/java/net/sf/jsqlparser/parser/feature/FeatureConfiguration.java
src/test/java/net/sf/jsqlparser/parser/CCJSqlParserUtilTest.java

Fixes #1582
Implement Parser Timeout Feature, e. g. `CCJSqlParserUtil.parse(sqlStr, parser -> parser.withTimeOut(60000));`
Add a special test failing after a long time only, to test TimeOut vs. Parser Exception

Configurable Parser Timeout via Feature

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

Adds support for "IF EXISTS" command in DROP COLUMN statement for PostgreSQL ([alter table docs](https://www.postgresql.org/docs/9.0/sql-altertable.html)).

add support for drop column if exists

---

src/main/java/net/sf/jsqlparser/parser/feature/Feature.java
src/main/java/net/sf/jsqlparser/util/validation/feature/FeaturesAllowed.java
src/main/java/net/sf/jsqlparser/util/validation/feature/OracleVersion.java
src/main/java/net/sf/jsqlparser/util/validation/feature/PostgresqlVersion.java
src/main/java/net/sf/jsqlparser/util/validation/validator/DeleteValidator.java

@manticore-projects would you please review the change?

Using own Feature - constant for "delete with returning" #1597

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

support hive alter sql : ALTER TABLE name ADD COLUMNS (col type,col2 type.....)
example :
``` sql
ALTER TABLE tablename add column (col  string comment 'aaaaa');
ALTER TABLE tablename add column (col  string comment 'aaaaa', col2 string comment 'bbbbb');
```

fix Issues: #1524  support hive alter sql : ALTER TABLE name ADD COLUMNS (col type,col2 type.....)

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/OverlapsCondition.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/OverlapsConditionTest.java

* Using the `ExpressionList` approach as discussed in the other PR
* No renames of existing classes
* Moved to `SQLCondition`

Closes #1604, added simple OVERLAPS support

---

src/main/java/net/sf/jsqlparser/expression/DateTimeLiteralExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Closes https://github.com/JSQLParser/JSqlParser/issues/1619
This add support for the `timestamptz` date time literal found in postgres derivative SQL. It's a commonly used abbreviation for the equivalent standard sql of `TIMESTAMP WITH TIME ZONE`

Support timestamptz dateliteral

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/SafeCastExpression.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/SafeCastExpressionTest.java

Add `SAFE_CAST` to support BigQuery SQL parser.

Support BigQuery SAFE_CAST (#1622)

---

src/main/java/net/sf/jsqlparser/parser/feature/Feature.java
src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/feature/MariaDbVersion.java
src/main/java/net/sf/jsqlparser/util/validation/feature/MySqlVersion.java
src/main/java/net/sf/jsqlparser/util/validation/feature/OracleVersion.java
src/main/java/net/sf/jsqlparser/util/validation/feature/PostgresqlVersion.java
src/main/java/net/sf/jsqlparser/util/validation/validator/SelectValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/for_update06.sql

This PR solves #1610 by adding the support to parse SKIP LOCKED tokens on SELECT FOR UPDATE statements

Support for SKIP LOCKED tokens on SELECT FOR UPDATE statements

---

src/main/java/net/sf/jsqlparser/statement/drop/Drop.java
src/main/java/net/sf/jsqlparser/util/deparser/DropDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/drop/DropTest.java

This is a fix for issue https://github.com/JSQLParser/JSqlParser/issues/1685.

Support DROP MATERIALIZED VIEW statements

---

.github/workflows/maven.yml

In our analysis, we observe that this target/surefire-report/ directory is generated but not later used during the CI build. Hence, we propose to disable generating this directory to save runtime.
The generation of this directory can be disabled by simply adding -DdisableXmlReport=true to the mvn command.

ignoring unnecessarily generated surefire report 

---

.github/workflows/maven.yml

In our analysis, we observe that there are a few directories and files (e.g., css, images, pmd.html) generated under target/site that are not used in CI. Because these are not accessed after its generation. Hence, we propose to disable the generation of these directories and files to save runtime. We found that the pmd plugin is generating this stuff. 
The generation of this directory can be disabled by simply adding -Dpmd.skip=true to the mvn command.

Ignoring unnecessarily generated by pmd plugin

---

build.gradle

New version of the JavaCC plugin is out: [release notes](https://github.com/javacc/javaccPlugin/releases/tag/javacc-gradle-plugin-3.0.0). Because the plugin ID changed, it won't be found by usual dependency update mechanisms, so I'm making  PRs manually to update the major projects on GitHub that are using an older version of the plugin.
The new version should make compilation of the parser a bit faster and improve compatibility with future releases of Gradle.
I locally checked that `./gradlew test` is successful with this change, but have not done any other testing.
Personally I'd suggest to use specific versions of plugins in the Gradle file rather than `latest.release`, but I did not change it here.
The warnings before and after seem to be the same:
```
Warning:  "RR" cannot be matched …
```

Update Gradle JavaCC parser to latest version (3.0.0)

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/CaseExpressionTest.java

Version: 4.7-SNAPSHOT
The problem was in an ELSE part of the WHEN expression. When we had a sub WHEN in ELSE and concatenate it with some another string:
`
CASE 
WHEN 1 = 2 
THEN 'string1'
ELSE 
CASE
WHEN 2 = 3
THEN 'string2'
ELSE 'first part'
END || 'second part'
END 
`

Fixing a problem with an OP_CONCAT in WhenExpression

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/update/UpdateTest.java
src/test/java/net/sf/jsqlparser/test/TestUtils.java

- add support for index hints in update statment for mysql
- Documentation: 
https://dev.mysql.com/doc/refman/8.0/en/update.html
https://dev.mysql.com/doc/refman/8.0/en/select.html
https://dev.mysql.com/doc/refman/8.0/en/join.html
- Example sql:
```sql
UPDATE demo FORCE INDEX (idx_demo) SET col1 = NULL WHERE col2 = 1
```

add support for index hints in Update statement for MySQL

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/TSQLLeftJoin.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/TSQLRightJoin.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Added support for 2 new operators supported:
\*= (LEFT OUTER JOIN)
=\* (RIGHT OUTER JOIN)
This is Transact-SQL syntax.
I thought it would be good to have that in addition to the Oracle (+)
Please note I don't handle misplaced usage of that operator

added support for T-SQL left and right joins (*= and =*)

---

src/main/java/net/sf/jsqlparser/parser/ParserKeywordsUtils.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

When I run unit tests, there are two failures:
1. ParserKeywordsUtilsTest#getAllKeywords failed to run. Because my os is windows and the regex in ParserKeywordsUtils#getAllKeywordsUsingRegex seems not support multi-os.
2. Compilation fails when using JDK 17. Nashorn has been deprecated after jdk11 and removed after jdk15.

Unit tests support multi-os and higher versions of jdk

---

src/main/java/net/sf/jsqlparser/statement/merge/Merge.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeInsert.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeUpdate.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/merge/MergeTest.java

This PR changes the parser to account for some Snowflake-specific aspects of the `MERGE` statement, namely:
- Tolerance for the `ON` condition not being wrapped in parentheses
- fixes #1315
- fixes #1880
- Support for an optional `AND` predicate after the `MATCHED`/`NOT MATCHED` part
See Snowflake's docs on MERGE: https://docs.snowflake.com/en/sql-reference/sql/merge - the new tests are derived from that doc.
- - -
With the `ON` logic, I did the simplest parser change which for existing cases (i.e. with parens), will now result in the `onCondition` being a `Parenthesis` containing the expression, where before it would have just been the expression (e.g. `EqualsTo` or whatever) itself. This feels innocuous to me, but if we consider this a breaking change and would prefer to avoid it, I can …

feat: add support for snowflake merge statements

---

src/site/sphinx/migration.rst

Found a typo in the 4.7 migration document. Trivial PR. Please merge.

Fix typo in migration.rst

---

src/main/java/net/sf/jsqlparser/statement/create/table/Index.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

closed https://github.com/JSQLParser/JSqlParser/issues/1909 Fix test `testAlterTableIndex586`, remove excess spaces.
According to MySQL documentation, KEY and INDEX are both INDEX

Fix: Support Drop Key

---

src/main/java/net/sf/jsqlparser/statement/create/index/CreateIndex.java
src/main/java/net/sf/jsqlparser/util/deparser/CreateIndexDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/create/CreateIndexTest.java

Fix: mysql and mariadb can use `index type` before `ON`

---

src/main/java/net/sf/jsqlparser/statement/create/table/Index.java
src/main/java/net/sf/jsqlparser/statement/create/table/NamedConstraint.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

Closed #1906, and format jjt file

Fix: [MySQL] Add `COMMENT` for `ALTER ADD`

---

src/main/java/net/sf/jsqlparser/parser/feature/Feature.java
src/main/java/net/sf/jsqlparser/statement/select/SelectVisitor.java
src/main/java/net/sf/jsqlparser/statement/select/SelectVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/select/TableStatement.java
src/main/java/net/sf/jsqlparser/util/AddAliasesVisitor.java
src/main/java/net/sf/jsqlparser/util/ConnectExpressionsVisitor.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/TableStatementDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/feature/FeaturesAllowed.java
src/main/java/net/sf/jsqlparser/util/validation/feature/MySqlVersion.java
src/main/java/net/sf/jsqlparser/util/validation/validator/SelectValidator.java
src/main/java/net/sf/jsqlparser/util/validation/validator/TableStatementValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/parser/CCJSqlParserUtilTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/java/net/sf/jsqlparser/util/deparser/StatementDeParserTest.java
src/test/java/net/sf/jsqlparser/util/validation/validator/TableStatementValidatorTest.java

closed #1836 
Treating it as a SELECT omits most of the code. This PR only completes the basic syntax, and according to the documentation, it also supports complex scenarios such as union, so it will not be considered temporarily.

feat: [MySQL] Support `TABLE STATEMENT`

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/java/net/sf/jsqlparser/statement/create/table/Index.java
src/main/java/net/sf/jsqlparser/statement/create/table/NamedConstraint.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/OracleHintTest.java
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

closed https://github.com/JSQLParser/JSqlParser/issues/1926, There is also a special MySQL case that is not convenient to implement.

Fix: ALTER INDEX COMMENT

---

src/main/java/net/sf/jsqlparser/parser/feature/Feature.java
src/main/java/net/sf/jsqlparser/statement/DescribeStatement.java
src/main/java/net/sf/jsqlparser/statement/ExplainStatement.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/feature/MySqlVersion.java
src/main/java/net/sf/jsqlparser/util/validation/validator/StatementValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/DescribeTest.java
src/test/java/net/sf/jsqlparser/util/validation/validator/StatementValidatorTest.java
src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/explain01.sql

close #1931, to support MySQL `{EXPLAIN | DESCRIBE | DESC}  tbl_name` 
it is necessary to use LOOKAHEAD(3), It made `explain01.sql` change. It seems to be expected?

Fix: DESC and EXPLAIN

---

src/main/java/net/sf/jsqlparser/statement/merge/Merge.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeDelete.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeInsert.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeOperation.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeOperationVisitor.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeOperationVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/merge/MergeUpdate.java
src/main/java/net/sf/jsqlparser/util/deparser/MergeDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/MergeValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/merge/MergeTest.java

This PR changes the parser to account for any number of `WHEN MATCHED` and/or `WHEN NOT MATCHED` clauses in a `MERGE` statement. This is most directly applicable to Snowflake. From their docs:
> A single MERGE statement can include multiple matching and not-matching clauses (i.e. WHEN MATCHED ... and WHEN NOT MATCHED ...).
```sql
MERGE INTO t1 USING t2 ON t1.t1Key = t2.t2Key
WHEN MATCHED AND t2.marked = 1 THEN DELETE
WHEN MATCHED AND t2.isNewStatus = 1 THEN UPDATE SET val = t2.newVal, status = t2.newStatus
WHEN MATCHED THEN UPDATE SET val = t2.newVal
WHEN NOT MATCHED THEN INSERT (val, status) VALUES (t2.newVal, t2.newStatus);
```
To achieve this, the parser now collects a list of `MergeOperation`s which can be a `WHEN MATCHED THEN DELETE` (newly added also), `WHEN MATCHED THEN UPDATE` or …

feat: support any number/order of merge operations

---

build.gradle
pom.xml

I use the Java module system with my project, but JSQLParser doesn't use modules. As a result, I need to use the --add-reads ALL-UNNAMED hack in order to depend on it.
Building a project with the Automatic-Module-Name feature allows it to work with the module system, but without actually depending on the module system itself. This change makes it easier to integrate JSQLParser with projects that are using the Java module system.
I ran both the Maven and Gradle builds and verified that `Automatic-Module-Name: net.sf.jsqlparser` appears in the jar's MANIFEST.MF file.

feat: Build with Automatic-Module-Name for compatibility with the Java module system.

---

src/main/java/net/sf/jsqlparser/statement/select/AllTableColumns.java
src/test/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapterTest.java

This fixes a regression introduced in change #4b4ae04f44ff18b669d0f30d637e5b7c64b085e4: feat: BigQuery Except(..) Replace(..) syntax
https://github.com/JSQLParser/JSqlParser/commit/4b4ae04f44ff18b669d0f30d637e5b7c64b085e4

fix: ExpressionVisitor.visit(AllTableColumns) method isn't being called.

---

src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

feat: support keyword "only" for postgresql

---

src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

feat: support Informix keywords "with no log"

---

src/main/java/net/sf/jsqlparser/statement/alter/Alter.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

Temporarily solve the issue 1875 #1875 . 
Refactoring may take more time. And in my opinion, we should discuss how to refactor.

fix: issue1875

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/java/net/sf/jsqlparser/statement/create/table/ColumnDefinition.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

Hi, I took a pass at fixing #1727 
This PR makes colDataType an optional value, so we can parse queries like
`ALTER TABLE table MODIFY col1 NULL`

fix: Fixes parsing failing for ALTER MODIFY queries not containing datatype

---

src/main/java/net/sf/jsqlparser/expression/DoubleValue.java
src/main/java/net/sf/jsqlparser/expression/LongValue.java
src/main/java/net/sf/jsqlparser/expression/TimeValue.java
src/test/java/net/sf/jsqlparser/expression/DoubleValueTest.java
src/test/java/net/sf/jsqlparser/expression/LongValueTest.java
src/test/java/net/sf/jsqlparser/expression/TimeValueTest.java

This PR intends to implement suitable guards for the constructors of the classes `DoubleValue`, `LongValue`, and `TimeValue`.
Both `null` and empty strings provided to their constructors fail, but they provide very different error messages (NullPointerException and StringIndexOutOfBoundsException),
which is neither sensible nor helpful in debugging.
This PR adds a guard to throw `IllegalArgumentException` for both cases in order to improve coherency and usefulness of the error messages.

Guard Values against null/empty values

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/test/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapterTest.java

This PR adds some null safety via `Optional`s to the `ExpressionVisitorAdapter` when handling certain analytic expressions.
The added test expression previously parsed fine but resulted in a `NullPointerException` when visited.

fix: make analytic expression visitor null-safe

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java

The ExpressionVisitorAdapter could handle Select to simplify the implementation of its children.
I've suggested an implementation that extracts portions from the ParenthesedSelect handling. Do take a look and let me know if this is fine.

Handle select in ExpressionVisitorAdapter

---

build.gradle
pom.xml
src/main/java/module-info.java

Add missing java.sql require

---

src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/MergeDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UpdateDeParser.java

My requirement scenario is ：
sql template "SELECT * FROM user WHERE name = :param_name AND status = :param_status"
where param_name and param_status both is null, need generated sql: "SELECT * FROM user"
where param_name is not null, param_status is null, need generated sql: "SELECT * FROM user WHERE name = ? "
so deParse where expression maybe is empty
deparseDistinctClause、deparseSelectItemsClause、deparseOrderByElementsClause requires two parameters ,
Parameter plainSelect mainly used to determine the current selection. like：
```java
@Override
protected void deparseDistinctClause(PlainSelect plainSelect, Distinct distinct) {
if (this.countSelect != plainSelect) {
super.deparseDistinctClause(plainSelect, distinct);
} else {
super.deparseDistinctClause(plainSelect, this.countDistinct);
} …
```

support custom DeParser

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/TableFunctionTest.java

SQL keywords are sometimes allowed as parameter names in table functions. For example, the following statement is valid on Snowflake:
```
INSERT INTO db.schema.target
(Name, FriendParent)
SELECT
i.DATA_VALUE:Name AS Name,
f1.Value:Parent:Name AS FriendParent
FROM
db.schema.source AS i,
flatten(input => i.DATA_VALUE:Friends, outer => true) AS f1
```
Note that the second named parameter passed to the table function `flatten` is `outer`, which is a SQL keyword, and it is unquoted.
Currently, statements like this fail to parse, I think because SQL keywords are not allowed as parameter names. However, as this is a valid statement, I'd like to be able to parse it.
The production in the grammar which handles named parameters is `OracleNamedFunctionParameter`. Currently, this is using the …

feat: Allow OUTER keyword as function parameter name

---

src/main/java/net/sf/jsqlparser/statement/truncate/Truncate.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/truncate/TruncateMultipleTablesTest.java
src/test/java/net/sf/jsqlparser/statement/truncate/TruncateTest.java

Looking to address this issue -> https://github.com/JSQLParser/JSqlParser/issues/2047
**Problem**
Truncate statements with multiple tables do not parse
**Solution**
- Add test scenarios
- Add `getTables`, `setTables` and `withTables` methods to the `Truncate` class
- Update `JSqlParserCC.jjt` + `StatementDeParser`

fix truncate parsing to capture multiple tables

---

src/test/java/net/sf/jsqlparser/statement/delete/DeleteTest.java
src/test/java/net/sf/jsqlparser/statement/insert/InsertTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/java/net/sf/jsqlparser/statement/update/UpdateTest.java

I have a future change in mind to do with CTEs. When I make the PR for this change I would like the unit tests changes (if any) to be simple and easy to understand. So, before I start to look at my CTE related change, I've added extra details to the `UpdateTest`, `InsertTest`, `DeleteTest` and `SelectTest` unit test scenarios.
There are zero functionality changes made here, only unit tests updates, I've been very careful not to change any SQL statements being tested.

chore adding extra details to unit test scenarios

---

src/test/java/net/sf/jsqlparser/statement/StatementSeparatorTest.java
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java
src/test/java/net/sf/jsqlparser/statement/merge/MergeTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Nothing major just clean up.
When I was working on [this change](https://github.com/JSQLParser/JSqlParser/pull/2055) I noticed a few surplus `System.out.println` lines. This PR removes them and cleans up a few other unit tests.

chore removing system.out.println lines + minor clean up of unit test scripts

---

src/main/java/net/sf/jsqlparser/expression/ConnectByPriorOperator.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/parser/ParserKeywordsUtils.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/connect_by08.sql
src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/connect_by09.sql
src/test/resources/net/sf/jsqlparser/statement/select/oracle-tests/connect_by10.sql

Encountered a failure with parsing queries having PRIOR in the select list (select t.id, prior t.id as parent_id ...).
Thought I would give it a try and fix it myself, but this is my first encounter with AST:s and parser libs in general so do keep that in mind.

Failure to parse query with PRIOR in select list

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

The current behaviour fails when it encounters `ADD COLUMNS` and merges everything in the `()` into one string with no whitespace.
So `ALTER TABLE catalog.table.name ADD COLUMNS (apples int)` becomes `ALTER TABLE catalog.table.name ADD COLUMNS (applesint)`.
This commit adds an understanding of `ALTER TABLE ... ADD COLUMNS` to the grammar.

Fix parsing `ALTER TABLE ... ADD COLUMNS (...)`

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

**Summary**
This PR fixes and enhances the parsing functionality for MySQL CONVERT statements in ALTER TABLE clauses in JSQLParser. It now supports a wider variety of CONVERT syntax.  
**Changes**
Updated AlterOperation enum to include CONVERT.
Modified the parser to correctly identify and handle the CONVERT clause, including optional COLLATE specifications.
Enhanced the parser to support the following[ ALTER TABLE syntax](https://dev.mysql.com/doc/refman/8.4/en/alter-table.html):
```sql
ALTER TABLE tbl_name
| [DEFAULT] CHARACTER SET [=] charset_name [COLLATE [=] collation_name]
| CONVERT TO CHARACTER SET charset_name [COLLATE collation_name]
```

Fix issue 2089: Enhance MySQL CONVERT Statement Parsing

---

src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

TablesNamesFinder did not have an implementation for `CREATE VIEW AS SELECT ...`

fix: [FEATURE] TablesNamesFinder does not support CREATE VIEW #2123

---

src/main/java/net/sf/jsqlparser/statement/select/WithItem.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

This PR adds support for MATERIALIZED CTEs: `WITH table AS MATERIALIZED ...`
Reference: https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-CTE-MATERIALIZATION

add support for MATERIALIZED in WITH clause

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/test/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapterTest.java

`ExpressionVisitorAdapter` was throwing a `NullPointerException` when a simple `INTERVAL` expression was provided, which didn't contain an actual expression (`.getExpression()` returns `null`).
Sample expression that causes the issue: `INTERVAL 1 DAY`
This PR adds validation around that code to fix this issue.

Fix null exception in ExpressionVisitorAdapter with simple INTERVAL expression

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/IsUnknownExpression.java
src/main/java/net/sf/jsqlparser/parser/ParserKeywordsUtils.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/site/sphinx/keywords.rst
src/test/java/net/sf/jsqlparser/expression/operators/relational/IsUnknownExpressionTest.java
src/test/java/net/sf/jsqlparser/statement/builder/ReflectionModelTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java
src/test/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidatorTest.java

This PR adds support for the `UNKNOWN` keyword and `IsUnknownExpression` in order to parse [`IS UNKNOWN`](https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html#operator_is) and [`IS NOT UNKNOWN`](https://dev.mysql.com/doc/refman/8.4/en/comparison-operators.html#operator_is-not) operations in MySQL.

feat: Support unknown keyword

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt

Support not equals operator with hat (^=), which is supported in Exasol https://docs.exasol.com/db/latest/sql_references/predicates/comparison_predicates.htm for example

Support not equals operator with a hat

---

.gitignore
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

When I test the FindTableNames, I created more complex SQL queries to ensure it works and able to extract correct set of tables out. So contribute such tests to avoid regressions introduced in future

Add more tests to TablesNamesFinderTest for SubqueryAliasesIssue1987

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

PostgreSQL supports expressions such as `posts.*` (all columns from the `posts` table) in many places, such as the `GROUP BY` clause.
For example, in this query:
```sql
select c.post_id, p.* from posts p inner join comments c on c.post_id = p.post_id group by p.post_id, c.post_id, p.*;
```
This PR adds support for AllTableColumns in PrimaryExpression.
I wasn't sure if PrimaryExpression is the best fit for this, so will be happy for suggestions on relocating it if there's a better expression group for it.

Add support for AllTableColumns in PrimaryExpression

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

This PR introduces a new parser rule `KeywordOrIdentifier()` to handle cases where certain keywords are used as identifiers. This addresses issues that arose after specific tokens like `NAME` were introduced as keywords.
While parsing a statement like:
```sql
ALTER TABLE test_table RENAME COLUMN name TO full_name;
```
the parser failed because `name` was recognized strictly as a `<K_NAME>` keyword after [this commit](https://github.com/JSQLParser/JSqlParser/commit/f932b8f9807530cebbcb280308fb05fe0dd1d983), instead of being allowed as an identifier.
- Introduced `KeywordOrIdentifier()` rule that accepts:
- `<S_IDENTIFIER>`
- `<S_QUOTED_IDENTIFIER>`
- Selected keywords like `<K_NAME>`, `<K_NEXT>`, `<K_VALUE>`, `<K_PUBLIC>`, `<K_STRING>`
- Additional tokens can be added as needed in the …

Allow specific keywords to be parsed as identifiers (fix issue with RENAME COLUMN)

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/select/FunctionAllColumns.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/ExpressionValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

PostgreSQL supports composite type expansion using `.*`, for example,  below query is valid in PostgreSQL:
```SQL
SELECT (pg_stat_file('postgresql.conf')).*
```
More generic one is like below one in queries or sub-queries:
```
SELECT (function_name(param1, ... paramN)).* FROM my_table ...
```
There might be multiple duplicated parentheses surround the function call, such as:
```
SELECT (((pg_stat_file('postgresql.conf')))).* -- this is same effect as one `()` surrounding
```
The PR is adding the support to parse/deparse this type of SQLs.

feat: add support SELECT all columns from function result

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt

Hi @manticore-projects,
This PR addresses multiple parser choice conflicts by increasing the LOOKAHEAD values in the index-related grammar rules.
✅ Resolved Warnings:
The following conflicts have been resolved:
```
Warning: Choice conflict in (...)* construct at line 7661, column 5.
Expansion nested within construct and expansion following construct
have common prefixes, one of which is: "WITH"
Consider using a lookahead of 2 or more for nested expansion.
Warning: Choice conflict involving two expansions at
line 7860, column 17 and line 7888, column 17 respectively.
A common prefix is: "SPATIAL" "COMMENT"
Consider using a lookahead of 3 or more for earlier expansion.
```
⚠️ Remaining Warnings:
However, the following two warnings still remain:
```
Warning: Choice conflict in [...] …
```

Resolve parser choice conflicts by adjusting lookahead in index-related rules

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

This PR adds support for two MySQL DDL statements:
`ALTER TABLE ADD CONSTRAINT UNIQUE KEY syntax`
`ALTER TABLE ALTER INDEX INVISIBLE syntax`
Previously, JSqlParser couldn't properly parse the following SQL statements:
```sql
ALTER TABLE sbtest1 ADD CONSTRAINT UNIQUE KEY ux_c3 (c3);
ALTER TABLE sbtest1 ALTER INDEX c4 INVISIBLE;
```
These are valid MySQL syntax for adding a unique constraint with a custom name and for making an index invisible to the query optimizer while keeping it maintained.
#2076

feat: enhance ALTER TABLE support with UNIQUE KEY and INVISIBLE index

---

src/main/java/net/sf/jsqlparser/parser/ParserKeywordsUtils.java
src/main/java/net/sf/jsqlparser/statement/select/Distinct.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/site/sphinx/keywords.rst
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

This PR adds support for the `DISTINCTROW` keyword available in [MySQL](https://dev.mysql.com/doc/refman/8.4/en/select.html) and [MariaDB](https://mariadb.com/kb/en/select/#distinct).
> ```sql
> SELECT
>     [ALL | DISTINCT | DISTINCTROW ]
>     ....
>     select_expr [, select_expr]
> ...
> ```

feat: support distinctrow keyword

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/resources/simple_parsing.txt

Supports SQL of the form:
```sql
SELECT * FROM tbl WHERE
day BETWEEN
CAST(CAST((NOW() + INTERVAL '-30 day') AS date) AS timestamptz)
AND
CAST(CAST((NOW() + INTERVAL '-1 day') AS date) AS timestamptz);
```

Fix[2288] - Support parenthesed expressions within Between

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/resources/simple_parsing.txt

`SELECT DATE_TRUNC('week',("schema"."tbl"."column" + INTERVAL '1 day')) FROM "schema"."tbl";` is parsing the `("schema"."tbl"."column" + INTERVAL '1 day')` as a LambdaFunction incorrectly, and crashes out. Increasing the lookahead depth by 1 ensures it fails to match on the `->` keyword (I believe), and falls into a simple expression instead.
Fixes #2290 
JMH
```
jmh {
includes = ['.*JSQLParserBenchmark.*']
warmupIterations = 2
fork = 5
iterations = 5
timeOnIteration = '5s'
}
```
After:
```
33.970 ±(99.9%) 1.773 ms/op [Average]
(min, avg, max) = (31.405, 33.970, 37.302), stdev = 2.367
CI (99.9%): [32.197, 35.743] (assumes normal distribution)
```
Before:
```
34.882 ±(99.9%) 1.923 ms/op [Average]
(min, avg, max) = (31.191, 34.882, 37.406), stdev = 2.567
CI (99.9%): [32.959, 36.805] …
```

Fix[2290] - Fix overeager lambda function parsing

---

src/main/java/net/sf/jsqlparser/statement/insert/ConflictActionType.java
src/main/java/net/sf/jsqlparser/statement/insert/Insert.java
src/main/java/net/sf/jsqlparser/statement/insert/InsertDuplicateAction.java
src/main/java/net/sf/jsqlparser/statement/upsert/Upsert.java
src/main/java/net/sf/jsqlparser/util/deparser/InsertDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UpsertDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/insert/InsertTest.java
src/test/java/net/sf/jsqlparser/statement/upsert/UpsertTest.java
src/test/java/net/sf/jsqlparser/util/deparser/StatementDeParserTest.java

Add a new feature to support opengauss "on duplicate key update nothing" syntax. I have executed mvn clean package locally, and all code format checks and unit tests have passed.

support opengauss "on duplicate key update nothing" grammar

---

src/main/java/net/sf/jsqlparser/parser/ParserKeywordsUtils.java
src/main/java/net/sf/jsqlparser/statement/select/WithFunctionDeclaration.java
src/main/java/net/sf/jsqlparser/statement/select/WithFunctionParameter.java
src/main/java/net/sf/jsqlparser/statement/select/WithItem.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/WithFunctionDeclarationTest.java
src/test/java/net/sf/jsqlparser/statement/select/WithFunctionParameterTest.java
src/test/java/net/sf/jsqlparser/statement/select/WithItemTest.java
src/test/resources/simple_parsing.txt

Fixes #2306 
Trino SQL allows you to specify User Defined functions in the WITH clause ahead of a statement. This adds support for this type of statement.

Fix[2306] - Adds support for Trino UDF

---

src/main/java/net/sf/jsqlparser/statement/delete/Delete.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/delete/DeleteTest.java

Added new features to support the complete delete using syntax of pg database, such as subqueries, etc.

Added new features to support the complete delete using syntax of pg database, such as subqueries, etc.
