JSQLParser/JSqlParser

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/OracleHint.java
src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapterTest.java
src/test/java/net/sf/jsqlparser/test/TestUtils.java
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

Single and multi line hints, i.e.
SELECT /*+ CHOOSE */ empno, ename, sal, job FROM emp;
SELECT --+ CHOOSE 
empno, ename, sal, job FROM emp;

Oracle Hint support for SELECT statements. 

---

src/main/java/net/sf/jsqlparser/statement/alter/Alter.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/alter/AlterTest.java

Support for alter table drop column/constraint

---

src/main/java/net/sf/jsqlparser/statement/insert/Insert.java
src/main/java/net/sf/jsqlparser/util/deparser/InsertDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/ReplaceDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/insert/InsertTest.java

support mysql like "INSERT IGNORE INTO ..."
http://dev.mysql.com/doc/refman/5.7/en/insert.html

support INSERT [LOW_PRIORITY | DELAYED | HIGH_PRIORITY] [IGNORE] 

---

pom.xml
src/main/java/net/sf/jsqlparser/statement/select/FromItemVisitor.java
src/main/java/net/sf/jsqlparser/statement/select/FromItemVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/select/TableFunction.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java

Added support of H2 table functions (http://www.h2database.com/html/features.html section 'Using a function as a table')
Ex: 'SELECT * FROM MATRIX(4)'

table functions

---

src/main/java/net/sf/jsqlparser/expression/AnalyticExpression.java
src/main/java/net/sf/jsqlparser/schema/Server.java
src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/util/deparser/ReplaceDeParser.java

This pull request is focused on resolving occurrences of Sonar rule squid:CommentedOutCodeLine - Sections of code should not be "commented out".
https://dev.eclipse.org/sonar/coding_rules#q=squid%3ACommentedOutCodeLine
George Kankava

squid:CommentedOutCodeLine - Sections of code should not be "commented out"

---

src/main/java/net/sf/jsqlparser/statement/create/table/CheckConstraint.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/alter/AlterTest.java
src/test/java/net/sf/jsqlparser/test/create/CreateTableTest.java

Implemented table check constraint for named constraints.
1. Added named constraint to create table.
2. Added check constraint to alter table statement.
3. Added CheckConstraint type.
Tests:
4. Added create table test.
5. Added alter table test.

Check constraint  on create / alter table for named constraints.

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/test/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapterTest.java

add null check before iterating `subSelect.getWithItemsList()`

fixed NPE in SubSelect without withItemsList in ExpressionVisitorAdapter

---

src/main/java/net/sf/jsqlparser/statement/select/Limit.java
src/main/java/net/sf/jsqlparser/util/deparser/LimitDeparser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java

add support for limit with jdbc index parameter. e.g. limit ?1, ?2

fixes #288

---

pom.xml
src/main/java/net/sf/jsqlparser/util/deparser/ExecuteDeParser.java
src/test/java/net/sf/jsqlparser/util/deparser/ExecuteDeParserTest.java

Fix issue #446

---

pom.xml
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/test/java/net/sf/jsqlparser/util/deparser/StatementDeParserTest.java

Fix issue #442

---

src/main/java/net/sf/jsqlparser/statement/insert/Insert.java
src/main/java/net/sf/jsqlparser/util/deparser/InsertDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/insert/InsertTest.java

Greetings, I generate this pull request to fix the issuse #424:
In addtion, I write test cases to test the INSERT query with ON DUPLICATE KEY UPDATE part.
Please look into my pull request and check whether the issue is solved.

fix issue #424 (INSERT with SET)

---

src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

Some edge cases that TableNamesFinder fails. For your review...

Fix for some cases where TableNamesFinder can't find tables

---

README.md

added a link to the visualize parsing section to have a visible debug mode (so users that create an issue can try to get us better output)

add debug note

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/MySQLValueListExpression.java
src/main/java/net/sf/jsqlparser/expression/ValueListExpression.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/test/select/SelectTest.java
src/test/java/net/sf/jsqlparser/util/TablesNamesFinderTest.java

JSQLPARSER-584: adds support for MySQL (a,b,...)OP(c,d,...) expression

---

src/main/java/net/sf/jsqlparser/schema/Column.java

JavaDoc for Column#getTable

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/IsBooleanExpression.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Example: SELECT col FROM tbl WHERE col IS TRUE

Adding support for IS [NOT] TRUE/FALSE expressions

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/arithmetic/IntegerDivision.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Adding support for MySQL's DIV operator, which allows to perform Integer Division (which is different than the "/" division operator).
More documentation here: https://dev.mysql.com/doc/refman/8.0/en/arithmetic-functions.html#operator_div

Adding support for the DIV operator

---

src/main/java/net/sf/jsqlparser/expression/ExpressionVisitor.java
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/FullTextSearch.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Example:
`SELECT MATCH (col1,col2,col3) AGAINST ('test' IN NATURAL LANGUAGE MODE) relevance FROM tbl`
Documentation: 
https://dev.mysql.com/doc/refman/5.7/en/fulltext-search.html

Add support for full text search (MATCH..AGAINST)

---

pom.xml
src/main/java/net/sf/jsqlparser/expression/ExpressionVisitorAdapter.java
src/main/java/net/sf/jsqlparser/schema/Table.java
src/main/java/net/sf/jsqlparser/statement/select/FromItem.java
src/main/java/net/sf/jsqlparser/statement/select/LateralSubSelect.java
src/main/java/net/sf/jsqlparser/statement/select/ParenthesisFromItem.java
src/main/java/net/sf/jsqlparser/statement/select/PivotVisitor.java
src/main/java/net/sf/jsqlparser/statement/select/PivotVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/select/SubJoin.java
src/main/java/net/sf/jsqlparser/statement/select/SubSelect.java
src/main/java/net/sf/jsqlparser/statement/select/TableFunction.java
src/main/java/net/sf/jsqlparser/statement/select/UnPivot.java
src/main/java/net/sf/jsqlparser/statement/select/ValuesList.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SpecialOracleTest.java

Added support for Oracle UNPIVOT keyword. Activated an already existing test file to test this feature: pivot01.sql. The test is successful.

Added support for Oracle UNPIVOT keyword.

---

src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Refer to documents on https://docs.oracle.com/cd/E17952_01/mysql-8.0-en/innodb-locking-reads.html#innodb-locking-reads-nowait-skip-locked

Support parsing SELECT FOR UPDATE NOWAIT

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterOperation.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

Support alter table rename

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SpecialOracleTest.java

Fixes the regressions introduced by #977

Fix CYCLE and GLOBAL token matching tests

---

src/main/java/net/sf/jsqlparser/util/deparser/AbstractDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/AlterDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/AlterViewDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/CreateIndexDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/CreateTableDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/CreateViewDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/DeclareStatementDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/DropDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/ExecuteDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/GrantDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/GroupByDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/InsertDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/LimitDeparser.java
src/main/java/net/sf/jsqlparser/util/deparser/OrderByDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/ReplaceDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/SetStatementDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/ShowColumnsStatementDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/ShowStatementDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UpdateDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UpsertDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UseStatementDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/ValuesStatementDeParser.java

add extend AbstractDeParser<T> to all deparsers

let all deparsers extend AbstractDeParser

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/resources/RUBiS-create-requests.txt

K_JSON is missing in ColDataType.

Fix issue #1020: JSON type in MySQL not supported in v3.2

---

src/main/java/net/sf/jsqlparser/statement/ReferentialAction.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/java/net/sf/jsqlparser/statement/create/table/ForeignKeyIndex.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

* implement COMMENT ON VIEW
* testcase "testCommentOnView"
https://github.com/JSQLParser/JSqlParser/issues/985

Support Foreign Key ON UPDATE CASCADE

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/drop/DropTest.java

bugfix issue #1036: supporting DROP SEQUENCE

---

src/main/java/net/sf/jsqlparser/statement/create/table/CreateTable.java
src/main/java/net/sf/jsqlparser/util/deparser/CreateTableDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/create/CreateTableTest.java

Support Create table LIKE. fixes #413

Support Create table LIKE

---

src/main/java/net/sf/jsqlparser/expression/AnalyticExpression.java
src/main/java/net/sf/jsqlparser/expression/Function.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

eg - SELECT count(UNIQUE col2) FROM mytable

supporting/fixing unique inside sql function such as count 

---

src/main/java/net/sf/jsqlparser/statement/delete/Delete.java
src/main/java/net/sf/jsqlparser/statement/merge/Merge.java
src/main/java/net/sf/jsqlparser/statement/update/Update.java
src/main/java/net/sf/jsqlparser/util/deparser/DeleteDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/UpdateDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/delete/DeleteTest.java
src/test/java/net/sf/jsqlparser/statement/merge/MergeTest.java
src/test/java/net/sf/jsqlparser/statement/update/UpdateTest.java

CLEAN PR with minimal change set to Master.

Implement WITH for DELETE, UPDATE and MERGE statements

---

nb-configuration.xml
src/main/java/net/sf/jsqlparser/expression/NextValExpression.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/builder/ReflectionModelTest.java
src/test/java/net/sf/jsqlparser/statement/insert/InsertTest.java

TSQL Compliant NEXT VALUE FOR sequence_id (but keeping the spurious NEXTVAL FOR expression)
This is a CLEAN PR with minimal change set against Master only.

TSQL Compliant NEXT VALUE FOR sequence_id

---

pmd-rules.xml
src/main/java/net/sf/jsqlparser/statement/StatementVisitor.java
src/main/java/net/sf/jsqlparser/statement/StatementVisitorAdapter.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterSession.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterSessionOperation.java
src/main/java/net/sf/jsqlparser/statement/create/view/CreateView.java
src/main/java/net/sf/jsqlparser/util/TablesNamesFinder.java
src/main/java/net/sf/jsqlparser/util/deparser/AlterSessionDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/CreateViewDeParser.java
src/main/java/net/sf/jsqlparser/util/deparser/StatementDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/AlterSessionValidator.java
src/main/java/net/sf/jsqlparser/util/validation/validator/StatementValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterSessionTest.java

Implement Oracle Alter Session Statements

---

src/main/java/net/sf/jsqlparser/expression/operators/relational/FullTextSearch.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/operators/relational/FullTextSearchExpressionTest.java

Allowes JdbcParameter or JdbcNamedParameter for MySQL FullTextSearch

---

src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Allows CASE ... ELSE ComplexExpression

---

src/main/java/net/sf/jsqlparser/expression/StringValue.java
src/main/java/net/sf/jsqlparser/expression/operators/relational/LikeExpression.java
src/main/java/net/sf/jsqlparser/util/deparser/ExpressionDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/expression/LikeExpressionTest.java
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

Issue #420 Like Expression with Escape Expression

---

src/main/java/net/sf/jsqlparser/statement/select/UnPivot.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/java/net/sf/jsqlparser/util/validation/validator/SelectValidator.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

hi greeting!
greate project! it helps a lot of my work.
add new test for this.
all test has passed.

Add support for oracle UnPivot when use multi columns at once.

---

src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/KSQLTest.java

- Add the EMIT CHANGES syntax used in KSQL.
- Closes #1126

Support EMIT CHANGES for KSQL

---

src/main/java/net/sf/jsqlparser/statement/select/PlainSelect.java
src/main/java/net/sf/jsqlparser/statement/select/SetOperationList.java
src/main/java/net/sf/jsqlparser/statement/select/WithIsolation.java
src/main/java/net/sf/jsqlparser/util/deparser/SelectDeParser.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/select/SelectTest.java

add support for db2 with ur option
```
SELECT * FROM mytable WHERE mytable.col = 9 WITH ur
```
Fixes #615

support for db2 with ur

---

pom.xml

https://github.com/JSQLParser/JSqlParser/issues/1483

 Reference to ruleset.xml #1483 

---

README.md
src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

Fixes #1517
(Although there is much more work to do on the `ALTER ... TABLE ... ALTER COLUMN ...` statement.)

Add support for `... ALTER COLUMN ... DROP DEFAULT`

---

src/main/java/net/sf/jsqlparser/statement/insert/InsertConflictAction.java

Add public Getter for `updateSets`
Fixes #1630

fix: add missing public Getter

---

build.gradle

Latest download plugin id "de.undercouch.download" version "5.3.0" Changed the download script.

Fixed download war script in the renderRR task

---

src/main/java/net/sf/jsqlparser/statement/alter/AlterExpression.java
src/main/java/net/sf/jsqlparser/statement/alter/AlterOperation.java
src/main/jjtree/net/sf/jsqlparser/parser/JSqlParserCC.jjt
src/test/java/net/sf/jsqlparser/statement/alter/AlterTest.java

closed https://github.com/JSQLParser/JSqlParser/issues/1815

feat: Support `RENAME INDEX` for MySQL, `RENAME CONSTRAINT` for PostgreSQL
